actions = [
    {"name": "go to sleep", "energy": 8, "health": 4, "happiness": 2},
    {"name": "exercise", "energy": -7, "health": 8, "happiness": 1},
    {"name": "drink", "energy": -6, "health": -14, "happiness": 9, "alcohol_addiction": 0.1},
    {"name": "watch tv", "energy": 1, "health": 0, "happiness": 3},
    {"name": "gamble", "energy": -2, "health": 0, "happiness": 6, "gambling_addiction": 0.125},
    {"name": "read a book", "energy": -1, "health": 2, "happiness": 4},
    {"name": "meditate", "energy": 2, "health": 3, "happiness": 3},
    {"name": "socialize", "energy": -3, "health": 2, "happiness": 5},
    {"name": "eat junk food", "energy": 1, "health": -5, "happiness": 7, "junk_food_addiction": 0.05},
    {"name": "cook a meal", "energy": -2, "health": 3, "happiness": 4},
    {"name": "take a walk", "energy": 3, "health": 4, "happiness": 4},
    {"name": "work", "energy": -5, "health": -1, "happiness": 4},
    {"name": "play video games", "energy": -3, "health": -1, "happiness": 8},
    {"name": "shop", "energy": -1, "health": 0, "happiness": 10, "shopping_addiction": 0.1},
    {"name": "go for a run", "energy": -6, "health": 8, "happiness": 3},
    {"name": "attend a class", "energy": -2, "health": 2, "happiness": 3},
    {"name": "visit a friend", "energy": -2, "health": 2, "happiness": 5},
    {"name": "listen to music", "energy": 1, "health": 0, "happiness": 3},
    {"name": "clean the house", "energy": -3, "health": 5, "happiness": -1},
    {"name": "play sports", "energy": -5, "health": 7, "happiness": 3},
    {"name": "stretch", "energy": 2, "health": 3, "happiness": 2},
    {"name": "drink water", "energy": 1, "health": 4, "happiness": 1},
    {"name": "take a shower", "energy": 2, "health": 3, "happiness": 4},
    {"name": "do yoga", "energy": -3, "health": 6, "happiness": 4},
    {"name": "go hiking", "energy": -6, "health": 8, "happiness": 6},
    {"name": "write in a journal", "energy": -1, "health": 1, "happiness": 5},
    {"name": "paint or draw", "energy": -2, "health": 1, "happiness": 7},
    {"name": "do a puzzle", "energy": -1, "health": 1, "happiness": 4},
    {"name": "gardening", "energy": -4, "health": 5, "happiness": 6},
    {"name": "take a nap", "energy": 5, "health": 2, "happiness": 2},
    {"name": "play an instrument", "energy": -2, "health": 1, "happiness": 6},
    {"name": "volunteer", "energy": -3, "health": 3, "happiness": 8},
    {"name": "go to a museum", "energy": -2, "health": 2, "happiness": 5},
    {"name": "visit a park", "energy": -1, "health": 3, "happiness": 6},
    {"name": "go swimming", "energy": -6, "health": 8, "happiness": 5},
    {"name": "go cycling", "energy": -5, "health": 7, "happiness": 5},
    {"name": "call a family member", "energy": -1, "health": 2, "happiness": 5},
    {"name": "do deep breathing exercises", "energy": 2, "health": 3, "happiness": 2},
    {"name": "admire nature", "energy": 1, "health": 1, "happiness": 6},
    {"name": "learn a new skill", "energy": -3, "health": 2, "happiness": 5},
    {"name": "attend a cultural event", "energy": -3, "health": 2, "happiness": 7},
    {"name": "practice gratitude", "energy": 1, "health": 2, "happiness": 5},
    {"name": "bake something", "energy": -3, "health": 3, "happiness": 5},
    {"name": "drink an energy drink", "energy": 10, "health": -3, "happiness": 0},
    {"name": "visit an animal shelter", "energy": -2, "health": 3, "happiness": 7},
    {"name": "watch educational videos", "energy": -1, "health": 1, "happiness": 4},
    {"name": "go stargazing", "energy": 1, "health": 1, "happiness": 6},
    {"name": "build something", "energy": -3, "health": 2, "happiness": 6},
    {"name": "go to a library", "energy": -2, "health": 2, "happiness": 5},
    {"name": "do a random act of kindness", "energy": -2, "health": 2, "happiness": 8},
    {"name": "walk barefoot in nature", "energy": 1, "health": 3, "happiness": 5},
    {"name": "practice a language", "energy": -2, "health": 2, "happiness": 5},
    {"name": "write a letter", "energy": -1, "health": 1, "happiness": 5},
    {"name": "go birdwatching", "energy": -1, "health": 2, "happiness": 5},
    {"name": "do a home improvement project", "energy": -4, "health": 3, "happiness": 6},
    {"name": "plan future goals", "energy": -2, "health": 1, "happiness": 5},
    {"name": "have a picnic", "energy": -3, "health": 3, "happiness": 6},
    {"name": "decorate a space", "energy": -3, "health": 2, "happiness": 6},
    {"name": "take care of a plant", "energy": -1, "health": 2, "happiness": 5}
]
